spring:
  application:
    name: "account"
  profiles:
    active: "csv-content-provider"
  datasource:
    url: jdbc:h2:mem:accounts
    username: sa
    password: password
    driverClassName: org.h2.Driver
  h2:
    console:
      enabled: true
      settings:
        trace: false
        web-allow-others: false
server:
  port: 0

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      default-zone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    hostname: localhost
    instance-id: ${spring.application.name}:${random.int}

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      probes:
        enabled: true
      show-details: always
      status:
        http-mapping:
          down: 500
          out_of_service: 503
          warning: 500
    shutdown:
      enabled: true

info:
  app:
    name: ${spring.application.name}
    description: This is the vid account application
    version: 0.0.1

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.apache.http: INFO
    org.ok.vid: INFO
    org.hibernate.SQL: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: INFO
    org.springframework.web.client.RestTemplate: DEBUG

springdoc:
  show-actuator: true

