spring:
  application:
    name: "USER"
  profiles:
    active: "csv-content-provider"
  datasource:
    url: jdbc:h2:mem:users
    username: sa
    password: password
    driverClassName: org.h2.Driver
  h2:
    console:
      enabled: true
      settings:
        trace: false
        web-allow-others: false
server:
  port: 0

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      default-zone: http://localhost:8761/eureka/
  instance:
    hostname: localhost

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      probes:
        enabled: true
      show-details: always
      status:
        http-mapping:
          down: 500
          out_of_service: 503
          warning: 500
    shutdown:
      enabled: true
  health:
    content:
      enabled: true

info:
  app:
    name: USER
    description: This is the vid user application
    version: 0.0.1

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.apache.http: INFO
    org.ok.vid: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

springdoc:
  show-actuator: true

