server:
  port: 8761

spring:
  application:
    name: "service-registry"

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      probes:
        enabled: true
      show-details: always
      status:
        http-mapping:
          down: 500
          out_of_service: 503
          warning: 500
    shutdown:
      enabled: true

info:
  app:
    name: ${spring.application.name}
    description: This is the vid service registry
    version: 0.0.1

logging:
  level:
    root: INFO
    org.ok.vid: INFO