spring:
  application:
    name: "gateway"

server:
  port: 0

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      default-zone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    hostname: localhost
    instance-id: ${spring.application.name}:${random.int}

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      probes:
        enabled: true
      show-details: always
      status:
        http-mapping:
          down: 500
          out_of_service: 503
          warning: 500
    shutdown:
      enabled: true
  health:
    content:
      enabled: true

info:
  app:
    name: ${spring.application.name}
    description: This is the vid service registry
    version: 0.0.1

logging:
  level:
    root: INFO
    org.ok.vid: INFO