global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ["localhost:9090"]
  - job_name: 'account'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 10s
    static_configs:
      - targets: [ 'localhost:51920', 'localhost:52547' ]
        labels:
          group: 'production'
  - job_name: 'user'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 10s
    static_configs:
      - targets: [ 'localhost:52630', 'localhost:52681' ]
        labels:
          group: 'production'
  - job_name: 'gateway'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 10s
    static_configs:
      - targets: [ 'localhost:52719' ]
        labels:
          group: 'production'
  - job_name: 'service-registry'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 10s
    static_configs:
      - targets: [ 'localhost:8761' ]
        labels:
          group: 'production'
