global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ["localhost:9090"]
  - job_name: 'account'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 10s
    static_configs:
      - targets: ['localhost:61408', 'localhost:61477']
        labels:
          group: 'production'
  - job_name: 'user'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 10s
    static_configs:
      - targets: [ 'localhost:61558', 'localhost:61712' ]
        labels:
          group: 'production'
